### Find All Gateways
GET http://localhost:3000/gateways

### Find Gateway By Id
GET http://localhost:3000/gateways/1

### Create Gateway
POST http://localhost:3000/gateways
Content-Type: application/json

{
  "serialNumber": "12345",
  "name": "Gateway 1",
  "ipv4Address": "192.168.1.1"
}

### Modify Gateway By Id
PUT http://localhost:3000/gateways/1
Content-Type: application/json

{
  "name": "Updated Gateway",
  "ipv4Address": "192.168.1.10"
}

### Delete Gateway By Id
DELETE http://localhost:3000/gateways/1

### Add Peripheral Device to Gateway
POST http://localhost:3000/gateways/1/devices
Content-Type: application/json

{
  "uid": 1,
  "vendor": "Device Vendor",
  "dateCreated": "2023-06-04T12:00:00Z",
  "status": "online"
}

### Remove Peripheral Device from Gateway
DELETE http://localhost:3000/gateways/1/devices/1
